// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjrtifgscybhcbyygbsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqcnRpZmdzY3liaGNieXlnYnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MzU5NDgsImV4cCI6MjA4ODExMTk0OH0.no3rv5gCk5ryxidltmvgPnOCxxTwCyFoCrZcNIWCwfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
